### ISSUE TITLE
Can this be included in the MantisBT/mantis-plugins repo ?

### ISSUE THREAD

**Issue by luzpaz** [infojunkie/MantisBT-Lightbox#2]
Thanks!

**Comment by dregad** [comment]
@infojunkie I created a group for the plugin, I let you transfer ownership of the plugin to mantisbt-plugins org if you wish. Let me know if you need help.

**Comment by infojunkie** [comment]
Thanks, I will fork the current repo into the mantisbt-plugins org, like I did for Slack: https://github.com/mantisbt-plugins/Slack

**Comment by dregad** [comment]
Great.

**Comment by infojunkie** [comment]
https://github.com/mantisbt-plugins/Lightbox
