### ISSUE TITLE
Branch for MantisBT 2.x core?

### ISSUE THREAD

**Issue by Kirill** [infojunkie/MantisBT-Lightbox#3]
Can you create new branch and adopt this plugin for new core 2.x?

**Comment by santoja** [comment]
Ok, I'll try the plugin in the new core and do the updates =).

**Comment by infojunkie** [comment]
The latest master works for 2.0.x. I moved the 1.2.x code to its own branch.

**Comment by Kirill** [comment]
Thanks. It's work very nice.
